name: API_CI

on:
  push:
    branches:
      - main

jobs:
  API_CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Setup node
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - run: yarn

      - name: Lint
        run: yarn lint

      - name: Integration test
        run: yarn test